site:
  title: Cemosis Docs
  url: https://docs.cemosis.fr
  start_page: stable@docs::index.adoc
  keys:
    google_analytics: 'UA-65761593-2'
content:
  sources:
  - url: https://prudhomm:b19655a097dd294bfda99ef447c342107d2b5e61@github.com/feelpp/ibat
    branches: master
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental-ui
asciidoc:
  attributes:
    project_version: 0.1
    deploymentRoot: ""
    numbered: true
    hide-uri-scheme: true
    feelpp: Feel++
    angiotk: AngioTK
    4fastsim: 4FastSim
    stem: latexmath
    hemotumpp: Hemotum++
    eye2brain: Eye2Brain
