site:
  title: Cemosis Docs
  url: https://docs.cemosis.fr
  start_page: cemosis::index.adoc
  keys:
    google_analytics: 'UA-65761593-2'
content:
  sources:
  - url: git@github.com:feelpp/docs.cemosis.fr.git
    branches: master
    start_path: cemosis
  - url: git@github.com:feelpp/swimmer.docs.git
    branches: master
    start_path: swimmer
  - url: git@github.com:feelpp/eye2brain.docs.git
    branches: master
    start_path: eye2brain
  - url: https://github.com/feelpp/hemotumpp.docs.git
    branches: master
    start_path: 'hemotumpp'
  - url: git@github.com:feelpp/ibat.docs.git
    branches: master
    start_path: 'ibat'
  - url: https://github.com/feelpp/book.hifimagnet
    branches: master
    start_path: 'docs/docs'
  - url: git@github.com:feelpp/internships.git
    branches: master
    start_path: '2018'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental-ui
asciidoc:
  attributes:
    project_version: 0.105
    deploymentRoot: ""
    numbered: true
    hide-uri-scheme: true
    feelpp: Feel++
    angiotk: AngioTK
    4fastsim: 4FastSim
    stem: latexmath
    hemotumpp: Hemotum++
    eye2brain: Eye2Brain
    omvs: Ocular Mathematical Virtual Simulator
    hifimagnet: HiFiMagnet
